///**
// * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
// * https://github.com/swagger-api/swagger-codegen
// * Do not edit the class manually.
// */
//package io.swagger.api;
//
//import io.swagger.model.Usuarios;
//import io.swagger.annotations.*;
//import org.springframework.http.ResponseEntity;
//import org.springframework.validation.annotation.Validated;
//import org.springframework.web.bind.annotation.PathVariable;
//import org.springframework.web.bind.annotation.RequestBody;
//import org.springframework.web.bind.annotation.RequestHeader;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.RequestPart;
//import org.springframework.web.multipart.MultipartFile;
//
//import javax.validation.Valid;
//import javax.validation.constraints.*;
//import java.util.List;
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-17T12:19:32.013Z")
//
//@Api(value = "usuarios", description = "the usuarios API")
//public interface UsuariosApi {
//
//    @ApiOperation(value = "Consulta todos os usuários", nickname = "consultaTodos", notes = "Esta operação tem como objetivo consultar todos os usuários cadastrados.", response = Usuarios.class, tags={ "Consulta", })
//    @ApiResponses(value = { 
//        @ApiResponse(code = 200, message = "Lista todos os usuários cadastrados do sistema.", response = Usuarios.class),
//        @ApiResponse(code = 400, message = "Consulta inválida"),
//        @ApiResponse(code = 401, message = "Consulta não autorizada") })
//    @RequestMapping(value = "/usuarios",
//        produces = { "application/json" }, 
//        consumes = { "application/json" },
//        method = RequestMethod.GET)
//    ResponseEntity<Usuarios> consultaTodos();
//
//}
